# AndroidX Support (Required for Compose, Hilt, Room, WorkManager)
android.useAndroidX=true
android.enableJetifier=true

# Gradle Memory (Fix OutOfMemoryError)
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

# Gradle Performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Kotlin
kotlin.code.style=official

# Compose
android.nonTransitiveRClass=true
