apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: school-transport
data:
  nginx.conf: |
    worker_processes auto;
    events { worker_connections 2048; }
    http {
      include /etc/nginx/mime.types;
      sendfile on;
      gzip on;
      
      upstream backend_cluster {
        server backend-api-service:3000;
      }

      server {
        listen 80;
        location /health/ {
          proxy_pass http://backend_cluster;
        }
        location /api/ {
          proxy_pass http://backend_cluster;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
