apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: school-transport-staging

namePrefix: staging-

resources:
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend-api
    spec:
      replicas: 2
